SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";



CREATE TABLE `admins` (
  `id` int(10) NOT NULL,
  `datetime` varchar(50) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `added_by` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



INSERT INTO `admins` (`id`, `datetime`, `username`, `password`, `added_by`) VALUES
(1, 'Sep-12-2018 22:34:36', 'admin', 'admin', 'admin');


CREATE TABLE `category` (
  `id` int(10) NOT NULL,
  `datetime` varchar(50) NOT NULL,
  `category` varchar(100) NOT NULL,
  `author` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



INSERT INTO `category` (`id`, `datetime`, `category`, `author`) VALUES
(1, '2018-09-08 12:18:05', 'سیاسی', 'admin'),
(2, '2018-09-08 12:18:05', 'کسب و کار', 'admin'),
(3, '2018-09-08 12:18:05', 'علمی', 'admin'),
(4, '2018-09-08 12:18:05', 'ورزش', 'admin'),
(5, '2018-09-08 12:18:05', 'جهان', 'admin'),
(6, '2018-09-08 12:18:05', 'تکنولوژی', 'admin'),
(7, '2018-09-08 12:18:05', 'سلامت', 'admin');


CREATE TABLE `comments` (
  `id` int(10) NOT NULL,
  `datetime` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `comment` varchar(500) NOT NULL,
  `approvedBy` varchar(100) NOT NULL,
  `status` varchar(5) NOT NULL,
  `postID` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO `comments` (`id`, `datetime`, `name`, `email`, `comment`, `approvedBy`, `status`, `postID`) VALUES
(1, 'Sep-15-2018 17:53:32', 'ali', 'a@a.com', 'Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex.', 'َAmir', 'off', 10),
(2, 'Sep-15-2018 17:57:16', 'ahmad', 'ahmad@a.com', 'Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex.', 'َAmir', 'off', 10),
(3, 'Sep-15-2018 17:57:35', 'zzzzz', 'z@z.com', 'Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex.\r\n                        ', 'َAmir', 'on', 10);



CREATE TABLE `posts` (
  `id` int(10) NOT NULL,
  `title` varchar(50) NOT NULL,
  `datetime` varchar(50) NOT NULL,
  `category` varchar(100) NOT NULL,
  `author` varchar(100) NOT NULL,
  `image` varchar(200) NOT NULL,
  `post` varchar(10000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



INSERT INTO `posts` (`id`, `title`, `datetime`, `category`, `author`, `image`, `post`) VALUES
(1, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:22:00', 'تکنولوژی', 'َAmir', 'datacenter_thumb_800x450_002.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(2, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:21:32', 'تکنولوژی', 'َAmir', 'datacenter_thumb_800x450_002.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(3, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:22:24', 'تکنولوژی', 'َAmir', 'datacenter_thumb_800x450_002.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(4, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:23:38', 'سیاسی', 'َAmir', 'politics.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(5, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:24:14', 'کسب و کار', 'َAmir', 'goals-for-your-business_512861902.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(6, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:25:02', 'سلامت', 'َAmir', '1528307634-health-science-mandatory-subject-5.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(7, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:25:16', 'ورزش', 'َAmir', 'bigstock-Four-Sports-a-lot-of-balls-an-50626115.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(8, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:27:18', 'علم', 'َAmir', 'science-onward-journey_v3-1.png', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(9, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:52:59', 'سیاسی', 'َAmir', 'politics.jpg', '                                                                                                                Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.                                                                                                '),
(10, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:31:30', 'جهان', 'َAmir', '1014_15-expat-family-travel-hacks-large.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(11, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:22:00', 'تکنولوژی', 'َAmir', 'datacenter_thumb_800x450_002.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(12, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:23:38', 'سیاسی', 'َAmir', 'politics.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(13, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:25:02', 'سلامت', 'َAmir', '1528307634-health-science-mandatory-subject-5.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(14, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:27:18', 'علم', 'َAmir', 'science-onward-journey_v3-1.png', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(15, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:31:30', 'جهان', 'َAmir', '1014_15-expat-family-travel-hacks-large.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(16, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:25:02', 'سلامت', 'َAmir', '1528307634-health-science-mandatory-subject-5.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(17, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:27:18', 'علم', 'َAmir', 'science-onward-journey_v3-1.png', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(18, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:31:30', 'جهان', 'َAmir', '1014_15-expat-family-travel-hacks-large.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(19, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:23:38', 'سیاسی', 'َAmir', 'politics.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(20, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:27:18', 'علم', 'َAmir', 'science-onward-journey_v3-1.png', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(21, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:22:00', 'تکنولوژی', 'َAmir', 'datacenter_thumb_800x450_002.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(22, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:22:24', 'تکنولوژی', 'َAmir', 'datacenter_thumb_800x450_002.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(23, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:24:14', 'کسب و کار', 'َAmir', 'goals-for-your-business_512861902.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(24, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:25:16', 'ورزش', 'َAmir', 'bigstock-Four-Sports-a-lot-of-balls-an-50626115.jpg', 'Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.'),
(25, 'Lorem ipsum dolor sit amet', 'Sep-15-2018 17:52:59', 'سیاسی', 'َAmir', 'politics.jpg', '                                                                                                                Lorem ipsum dolor sit amet, invenire rationibus mnesarchum no usu, ea quod vero mediocrem usu. Liber mucius dictas sed ei, ne has audire lobortis, pro ad sale nullam. Quod argumentum est ut, nulla nostro imperdiet vis ea. Te enim inani mediocritatem mea, ut sea assentior consectetuer signiferumque.Ex vel ubique fastidii reformidans, nam tale corrumpit quaerendum ad. Ei mea rebum commodo equidem, debitis albucius dignissim eu per. Justo harum sensibus id vel. Sea quando perpetua ea. Iusto homero insolens qui ad.Iuvaret invidunt suscipiantur ex his, eum id iusto fabulas persequeris, has no ignota mandamus. Vel evertitur gloriatur ad, quaeque alienum persequeris nec ad. Iriure singulis has ut. No aliquam consulatu mei, an vix dicat equidem facilisi. Primis dolorem cum no, ei mutat munere eos, aeterno appetere sit ea.Consul causae aeterno sit ex, ut mea tollit animal. Summo virtute deseruisse an sit, pro reque periculis temporibus ne. In recusabo mnesarchum instructior eam, duo nemore efficiantur in, magna offendit an vis. Nibh melius ceteros vim in. Tempor tacimates necessitatibus sit ne.Ne errem officiis duo. Usu virtute atomorum ad, viris veniam tamquam eos ex. Vivendum verterem ei sit, agam possim accumsan est ea. Nec latine eripuit suavitate te, quidam accusam an vim, per aeque salutandi eu.                                                                                                ');


ALTER TABLE `admins`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `postID` (`postID`),
  ADD KEY `postID_2` (`postID`),
  ADD KEY `status` (`status`),
  ADD KEY `postID_3` (`postID`);

ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `admins`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;


ALTER TABLE `category`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

ALTER TABLE `comments`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

ALTER TABLE `posts`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;

ALTER TABLE `comments`
  ADD CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`postID`) REFERENCES `posts` (`id`);
COMMIT;


